In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from bs4 import BeautifulSoup as BS
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Kamana Sewa Bikas bank 1

In [4]:
url = "https://www.kamanasewabank.com/interest-rates"

In [5]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [6]:
"""
* a dictionary for a bank
* name a key of it as table name, value as dictionary {head: value}
* i.e { deposit:{
  S.N.: [1],
  Saving Deposit: [Mahila Bachat],
},
Loan:{
  S.N.: [1],
  Interest Name: [Student],

}

}
"""
kamana_dict = {}
kamana_intrst = []
table = soup.find("table")
for table in soup.findAll("table"):
  # headers = [str(th.text.strip()) for th in table.find("thead").findAll("th")]
  # # kamana_dict["Deposit"] = {}

  # tmp_dict = {head:[] for head in headers}

  # # table.find("tr").text

  # # lambda fxn to clean each word
  # stripper = lambda  s: " ".join([ss.strip() for ss in s.split(" ")])

  # for tr in table.findAll("tr")[1:]:
  #   col_data = [stripper(td.text) for td in tr.findAll("td")]
  #   for h, c in zip(headers, col_data):
  #     tmp_dict[h].append(c)
  
  df = pd.read_html(str(table))[0]
  kamana_intrst.append(df)

  # print(col_data)
  # break
# tmp_dict, headers
# kamana_dict["deposit"] = tmp_dict
kamana_intrst

[    S.N.  ...       PAYMENT ON
 0      1  ...  Quarterly Basis
 1      2  ...  Quarterly Basis
 2      3  ...  Quarterly Basis
 3      4  ...  Quarterly Basis
 4      5  ...  Quarterly Basis
 5      6  ...  Quarterly Basis
 6      7  ...  Quarterly Basis
 7      8  ...  Quarterly Basis
 8      9  ...  Quarterly Basis
 9     10  ...  Quarterly Basis
 10    11  ...  Quarterly Basis
 11    12  ...  Quarterly Basis
 12    13  ...  Quarterly Basis
 13    14  ...  Quarterly Basis
 14    15  ...  Quarterly Basis
 15    16  ...  Quarterly Basis
 16    17  ...  Quarterly Basis

 [17 rows x 5 columns],     S.N.  ...                           PAYMENT ON
 0      1  ...                                  NaN
 1      1  ...  Monthly or Quarterly or at Maturity
 2      1  ...  Monthly or Quarterly or at Maturity
 3      1  ...  Monthly or Quarterly or at Maturity
 4      1  ...  Monthly or Quarterly or at Maturity
 5      1  ...  Monthly or Quarterly or at Maturity
 6      2  ...                                  NaN
 7      2  ...  Monthly or Quarterly or at Maturity
 8      2  ...  Monthly or Quarterly or at Maturity
 9      2  ...  Monthly or Quarterly or at Maturity
 10     2  ...  Monthly or Quarterly or at Maturity

 [11 rows x 5 columns],    S.N.  ... PAYMENT ON
 0     1  ...  Quarterly
 1     2  ...  Quarterly

 [2 rows x 5 columns],                                                 S.N.  ... INTEREST RATE (PER ANNUM ) (Base Rate+ Premium )(%)
 0                                                  1  ...                                         Negotiable
 1                                                  2  ...  upto 3% on coupon rate or Base Rate whichever ...
 2                                                  3  ...                         As per consortium decision
 3                                                  4  ...                                Base Rate + upto 5%
 4                                                  5  ...                                Base Rate + upto 5%
 5                          Base Rate as of Magh 2077  ...                                              8.68%
 6       *Rs 100 will be deposited by the bank itself  ...       *Rs 100 will be deposited by the bank itself
 7  Note: Fixed Rate for Personal Term Loans - 13....  ...  Note: Fixed Rate for Personal Term Loans - 13....

 [8 rows x 5 columns],       SN                      As on quarter end Base Rate
 0    1.0    Base Rate (BR) as on Poush end 2077     9.05%
 1    2.0   Base Rate (BR) as on Ashwin end 2077     9.28%
 2    3.0    Base Rate (BR) as on Ashad end 2077    10.55%
 3    4.0  Base Rate (BR) as on Chaitra end 2076    11.79%
 4    5.0    Base Rate (BR) as on Paush end 2076    11.86%
 5    6.0   Base Rate (BR) as on Ashwin end 2076    11.86%
 6    7.0   ​Base Rate (BR) as on Ashad End 2076    11.59%
 7    8.0  Base Rate (BR) as on Chaitra End 2075    11.65%
 8    9.0    Base Rate (BR) as on Paush End 2075    11.59%
 9   10.0   Base Rate (BR) as on Ashwin End 2075    11.83%
 10   NaN                                    NaN       NaN
 11  11.0    Base Rate (BR) as on Ashad End 2075    12.58%
 12  12.0  Base Rate (BR) as on Chaitra End 2074    12.17%
 13  13.0   ​Base Rate (BR) as on Paush End 2074    11.92%
 14  14.0    Base Rate (BR) as on Ashad End 2074    11.71%]

In [19]:
for i, df in enumerate(kamana_intrst):
  df.to_csv(f"kamana{i}.csv")
kamana_intrst[0] # Saving Deposit, Fixed Deposit, Recurring Deposit, Loan, base rate

    S.N.  ...       PAYMENT ON
0      1  ...  Quarterly Basis
1      2  ...  Quarterly Basis
2      3  ...  Quarterly Basis
3      4  ...  Quarterly Basis
4      5  ...  Quarterly Basis
5      6  ...  Quarterly Basis
6      7  ...  Quarterly Basis
7      8  ...  Quarterly Basis
8      9  ...  Quarterly Basis
9     10  ...  Quarterly Basis
10    11  ...  Quarterly Basis
11    12  ...  Quarterly Basis
12    13  ...  Quarterly Basis
13    14  ...  Quarterly Basis
14    15  ...  Quarterly Basis
15    16  ...  Quarterly Basis
16    17  ...  Quarterly Basis

[17 rows x 5 columns]

In [ ]:
df = pd.read_html(str(table))[0]
df

      SN                      As on quarter end Base Rate
0    1.0    Base Rate (BR) as on Poush end 2077     9.05%
1    2.0   Base Rate (BR) as on Ashwin end 2077     9.28%
2    3.0    Base Rate (BR) as on Ashad end 2077    10.55%
3    4.0  Base Rate (BR) as on Chaitra end 2076    11.79%
4    5.0    Base Rate (BR) as on Paush end 2076    11.86%
5    6.0   Base Rate (BR) as on Ashwin end 2076    11.86%
6    7.0   ​Base Rate (BR) as on Ashad End 2076    11.59%
7    8.0  Base Rate (BR) as on Chaitra End 2075    11.65%
8    9.0    Base Rate (BR) as on Paush End 2075    11.59%
9   10.0   Base Rate (BR) as on Ashwin End 2075    11.83%
10   NaN                                    NaN       NaN
11  11.0    Base Rate (BR) as on Ashad End 2075    12.58%
12  12.0  Base Rate (BR) as on Chaitra End 2074    12.17%
13  13.0   ​Base Rate (BR) as on Paush End 2074    11.92%
14  14.0    Base Rate (BR) as on Ashad End 2074    11.71%

# Muktinath Bikas Bank 2

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from bs4 import BeautifulSoup as BS
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

In [21]:
url = "https://www.muktinathbank.com.np/interest-rates"

In [22]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [23]:
muktinath_intrst = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  muktinath_intrst.append(df)

In [25]:
muktinath_intrst[2] # hard code the table name

                                         PRODUCT                             FLOATING INTEREST BAND
0                               1. Business Loan                    Base Rate + Premium up to 4.50%
1                            2. Agriculture Loan                    Base Rate + Premium up to 4.50%
2     3. Home Loan (new construction & purchase)                    Base Rate + Premium up to 4.50%
3                            4. Home Equity Loan                    Base Rate + Premium up to 4.50%
4                                   5. Auto Loan                    Base Rate + Premium up to 5.00%
5                      6. Hirepurchase Loan(new)                    Base Rate + Premium up to 5.00%
6                      7. Hirepurchase Loan(old)                    Base Rate + Premium up to 5.00%
7                            8. Real Estate Loan                    Base Rate + Premium up to 5.00%
8                               9. Personal Loan                    Base Rate + Premium up to 5.00%
9                                  10.Share Loan                    Base Rate + Premium up to 4.50%
10                              11.Mortgage Loan                    Base Rate + Premium up to 5.00%
11                          12.Professional Loan                    Base Rate + Premium up to 4.50%
12           13. Muktinath Sulav Byawasaya Karja                    Base Rate + Premium up to 4.50%
13                             14. Consumer Loan                    Base Rate + Premium up to 5.00%
14                                 15. Gold Loan                    Base Rate + Premium up to 4.50%
15                               16. Other Loans                    Base Rate + Premium up to 5.00%
16             17. Small & Micro Credit (Retail)                    Base Rate + Premium up to 5.50%
17          18. Small & Micro Credit (wholesale)                    Base Rate + Premium up to 2.00%
18  19. Loan Against Fixed Deposit (upto 90.00%)  Coupon Rate Plus 2.00% or Base Rate whichever ...

# NIC Asia Bank 3

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from bs4 import BeautifulSoup as BS
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

In [ ]:
url = "https://www.nicasiabank.com/interest-rates"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
NICasia_intrst = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  NICasia_intrst.append(df)

In [ ]:
NICasia_intrst[0]

    S.N  ... Interest Rate(%p.a)
0     1  ...               2.10%
1     2  ...               2.10%
2     3  ...               2.10%
3     4  ...               2.10%
4     5  ...               2.10%
..  ...  ...                 ...
88   89  ...               3.50%
89   90  ...               3.50%
90   91  ...               3.50%
91   92  ...               3.50%
92   93  ...               3.50%

[93 rows x 4 columns]

# Investment Bank 4

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from bs4 import BeautifulSoup as BS
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

In [ ]:
url = "https://nibl.com.np/personal-banking/rates-and-fees/interest-rates"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
Invest_intrest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  Invest_intrest.append(df)

In [ ]:
Invest_intrest[0]

          0          1          2                3                          4
0   2074-75     Period  Base Rate  Interest Spread                    Remarks
1   2074-75  Quarter 1      8.91%            4.32%                        NaN
2   2074-75  Quarter 2      9.00%            4.05%                        NaN
3   2074-75  Quarter 3      9.12%            4.28%                        NaN
4   2074-75  Quarter 4      9.02%            4.59%                        NaN
5       NaN        NaN        NaN              NaN                        NaN
6   2075-76     Period  Base Rate  Interest Spread                    Remarks
7   2075-76  Quarter 1      9.03%            4.53%                        NaN
8   2075-76  Quarter 2      8.96%            4.24%                        NaN
9   2075-76  Quarter 3      8.54%            4.24%                        NaN
10  2075-76  Quarter 4      8.33%            4.38%                        NaN
11      NaN        NaN        NaN              NaN                        NaN
12  2076-77     Period  Base Rate  Interest Spread                    Remarks
13  2076-77  Quarter 1      8.48%            4.36%                        NaN
14  2076-77  Quarter 2      8.53%            5.16%  Excluding Gov, Securities
15  2076-77  Quarter 2      8.53%            4.41%  Including Gov. Securities
16  2076-77  Quarter 3      8.53%            5.01%  Excluding Gov, Securities
17  2076-77  Quarter 3      8.53%            4.18%  Including Gov. Securities
18  2076-77  Quarter 4      7.51%            3.99%                        NaN
19      NaN        NaN        NaN              NaN                        NaN
20  2077-78     Period  Base Rate  Interest Spread                    Remarks
21  2077-78  Quarter 1      7.19%            4.14%                        NaN

# Civil Bank 5

In [ ]:
url = "https://www.civilbank.com.np/financial-information/interest-rates"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
civil_intrest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  civil_intrest.append(df)

In [ ]:
civil_intrest[0]

# Himalayan Bank 6

In [ ]:
url = "https://www.himalayanbank.com/en/rates/deposit-products-rate"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
himalayan_intrest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  himalayan_intrest.append(df)

In [ ]:
himalayan_intrest[0]

                        Savings Deposit  %Per Annum
0                  LCY Savings - Normal        2.00
1                   LCY Savings - Himal        3.00
2                 LCY Savings - Bishesh        3.50
3               Premium Savings Account        3.50
4         Super Premium Savings Account        3.75
5                 Shareholder's Savings        3.25
6                   Himal Remit Savings        3.50
7                        Family Savings        3.50
8              Mero Pahilo Bachat Khata        3.00
9               Special Payroll Account        3.50
10                      HBL Nari Bachat        3.50
11              Subidha Savings Account        4.00
12  Exclusive Privilege Savings Account        4.00
13              Jeevan Surakchya Bachat        3.00
14                 LCY Savings - Normal        2.00
15                  LCY Savings - Himal        3.00
16                LCY Savings - Bishesh        3.50
17              Premium Savings Account        3.50
18        Super Premium Savings Account        3.75
19                Shareholder's Savings        3.25
20                  Himal Remit Savings        3.50
21                       Family Savings        3.50
22             Mero Pahilo Bachat Khata        3.00
23              Special Payroll Account        3.50
24                      HBL Nari Bachat        3.50
25              Subidha Savings Account        4.00
26  Exclusive Privilege Savings Account        4.00
27              Jeevan Surakchya Bachat        3.00

# Kumari Bank 7

In [ ]:
url = "https://www.kumaribank.com/interest-rate-deposits"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
kumari_intrest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  kumari_intrest.append(df)

In [ ]:
kumari_intrest[0]

# Sanima Bikas Bank 8

In [ ]:
url = "https://www.sanimabank.com/interest-rate"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
sanima_intrest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  sanima_intrest.append(df)

In [ ]:
sanima_intrest[0]

   Unnamed: 0_level_0  ...                            Interest Payment
   Unnamed: 0_level_1  ...                  Interest Payment Frequency
   Unnamed: 0_level_2  ...                          Unnamed: 5_level_2
   Unnamed: 0_level_3  ...                          Unnamed: 5_level_3
   Unnamed: 0_level_4  ...                          Unnamed: 5_level_4
   Unnamed: 0_level_5  ...                          Unnamed: 5_level_5
   Unnamed: 0_level_6  ...                          Unnamed: 5_level_6
   Unnamed: 0_level_7  ...                          Unnamed: 5_level_7
   Unnamed: 0_level_8  ...                          Unnamed: 5_level_8
   Unnamed: 0_level_9  ...                          Unnamed: 5_level_9
0                 NaN  ...                                   Quarterly
1                 NaN  ...                                   Quarterly
2                 NaN  ...                                   Quarterly
3                 NaN  ...                                   Quarterly
4                 NaN  ...                                   Quarterly
..                ...  ...                                         ...
80                NaN  ...                                         NaN
81                NaN  ...                                         NaN
82                NaN  ...  L. Fixed Rate For Individual Loan (% P.A.)
83                NaN  ...                           For Above 3 Years
84                NaN  ...                                    Up to 13

[85 rows x 6 columns]

# Garima bikas Bank 9

In [ ]:
url = "https://garimabank.com.np/interest-rates.html"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
banijya_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  banijya_interest.append(df)

In [ ]:
banijya_interest[0]

# Prime commercial bank 10

In [ ]:
url = "https://www.primebank.com.np/interest/details/78"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
prime_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  prime_interest.append(df)

In [ ]:
prime_interest

# Himalayan Bank  11

In [ ]:
url = "https://himalayanbank.com/en/rates/deposit-products-rate"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
himalayan_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  himalayan_interest.append(df)

In [ ]:
himalayan_interest

# Sunrise Bank 12

In [ ]:
url = "https://www.sunrisebank.com.np/interest-rate"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
sunrise_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  sunrise_interest.append(df)

In [ ]:
sunrise_interest

# Citizen Bank 13

In [ ]:
url = "https://www.ctznbank.com/interest-rate"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
citizen_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  citizen_interest.append(df)

In [ ]:
citizen_interest

# Everest bank 14

In [ ]:
url = "https://everestbankltd.com/supports/interest-and-rates/interest-rates-deposit/"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
everest_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  everest_interest.append(df)

In [ ]:
everest_interest

# Agriculture Bank 15

In [ ]:
url = "https://www.agricbank.com/customer-care/financials/current-rates/"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
agricul_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  agricul_interest.append(df)

In [ ]:
agricul_interest

# Laxmi Bank 16

In [ ]:
url = "https://www.laxmibank.com/rates/interest-rates/"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
laxmi_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  laxmi_interest.append(df)

In [ ]:
laxmi_interest

# Parbhu Bikas Bank 17

In [ ]:
url = "https://www.prabhubank.com/interest-rates"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
parbhu_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  parbhu_interest.append(df)

In [ ]:
parbhu_interest

# NMB Bank 18

In [ ]:
url = "https://nmbbanknepal.com/interest-rate"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
parbhu_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  parbhu_interest.append(df)

In [ ]:
parbhu_interest

# Garima Bank 19

In [ ]:
url = "https://garimabank.com.np/interest-rates.html"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
garima_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  garima_interest.append(df)

In [ ]:
garima_interest

# Jyoti Bank 20

In [ ]:
url = "https://jbbl.com.np/quick-links/interest-rate"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
jyoti_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  jyoti_interest.append(df)

In [ ]:
jyoti_interest

# Lumbini Bank 21

In [ ]:
url = "https://www.lumbinibikasbank.com/navigation/interest-rate"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
lumbini_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  lumbini_interest.append(df)

In [ ]:
lumbini_interest

# Machhapuchre Bank 22

In [ ]:
url = "https://www.machbank.com/interest-rate"

In [ ]:
http = urllib3.PoolManager()
http.addheaders = [('User-agent', 'Mozilla/61.0')]
web_page = http.request('GET', url)
soup = BS(web_page.data, 'html5lib')

In [ ]:
machhapuchre_interest = []
table = soup.find("table")
for table in soup.findAll("table"):
  df = pd.read_html(str(table))[0]
  machhapuchre_interest.append(df)

In [ ]:
machhapuchre_interest